version: "3.6"
services:
  testpost:
    container_name: testpost
    image: index.docker.io/aleksioprime/testpost
    command: python app.py
    volumes:
      - ./instance:/app/instance
    networks:
      - main
    ports:
      - "5000:5000"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
networks:
  main:
    driver: bridge